Repository kubernetes-sigs/blixt, pull requests merged in 2023-10, with the labels that each got.

#117 udproute: add support for round-robin load balancing
  Makefile
  config/samples/udproute/udproute.yaml
  config/tests/udproute-rr/kustomization.yaml
  config/tests/udproute/kustomization.yaml
  controllers/tcproute_controller.go
  controllers/udproute_controller.go
  dataplane/api-server/proto/backends.proto
  dataplane/api-server/src/backends.rs
  dataplane/api-server/src/lib.rs
  dataplane/api-server/src/server.rs
  dataplane/common/src/lib.rs
  dataplane/ebpf/src/ingress/tcp.rs
  dataplane/ebpf/src/ingress/udp.rs
  dataplane/ebpf/src/main.rs
  dataplane/loader/src/main.rs
  dataplane/xtask/src/grpc.rs
  internal/dataplane/client/backends.pb.go
  internal/dataplane/client/backends_grpc.pb.go
  internal/dataplane/client/utils.go
  test/integration/udproute_test.go
Labels: lgtm, cncf-cla: yes, tide/merge-method-squash, approved, size/XL

#121 Bpfd integration
  .github/workflows/test.yaml
  Makefile
  config/bpf-bytecode/kustomization.yaml
  config/bpf-bytecode/tc-egress.yaml
  config/bpf-bytecode/tc-ingress.yaml
  config/bpfd-install/kustomization.yaml
  config/bpfd-install/patch.yaml
  config/bpfd/bpfd.yaml
  config/bpfd/kustomization.yaml
  config/tests/integration-bpfd/kustomization.yaml
  dataplane/.cargo/config.toml
  dataplane/Makefile
  dataplane/api-server/src/backends.rs
  dataplane/ebpf/.cargo/config.toml
  dataplane/ebpf/Cargo.toml
  dataplane/ebpf/src/main.rs
  dataplane/loader/src/main.rs
  test/integration/suite_test.go
Labels: lgtm, cncf-cla: yes, approved, size/XL

#93 Add support for multiple gRPC client management
  Dockerfile
  controllers/dataplane_controller.go
  controllers/tcproute_controller.go
  controllers/udproute_controller.go
  go.mod
  go.sum
  internal/dataplane/client/client.go
  main.go
Labels: feature, area/dataplane, area/controlplane, lgtm, cncf-cla: yes, tide/merge-method-squash, approved, size/XL
